export const categories = [
  {
    name: 'Greetings',
    words: [
      { english: 'Hello', swedish: 'Hej' },
      { english: 'Good morning', swedish: 'God morgon' },
      { english: 'Good evening', swedish: 'God kväll' },
      { english: 'Good night', swedish: 'God natt' },
      { english: 'Goodbye', swedish: 'Hejdå' },
      { english: 'See you later', swedish: 'Vi ses senare' },
      { english: 'Thank you', swedish: 'Tack' },
      { english: 'Thanks a lot', swedish: 'Tack så mycket' },
      { english: 'You’re welcome', swedish: 'Varsågod' },
      { english: 'Please', swedish: 'Snälla' },
      { english: 'Excuse me', swedish: 'Ursäkta mig' },
      { english: 'Sorry', swedish: 'Förlåt' },
      { english: 'Yes', swedish: 'Ja' },
      { english: 'No', swedish: 'Nej' },
      { english: 'Maybe', swedish: 'Kanske' },
      { english: 'How are you?', swedish: 'Hur mår du?' },
      { english: 'I am fine, thank you', swedish: 'Jag mår bra, tack' },
      { english: 'What is your name?', swedish: 'Vad heter du?' },
      { english: 'My name is...', swedish: 'Jag heter...' },
      { english: 'Nice to meet you', swedish: 'Trevligt att träffas' },
      { english: 'How’s it going?', swedish: 'Hur går det?' },
      { english: 'Long time no see', swedish: 'Länge sedan sist' },
      { english: 'What’s up?', swedish: 'Vad händer?' },
      { english: 'Good to see you', swedish: 'Kul att se dig' },
      { english: 'Take care', swedish: 'Ta hand om dig' },
      { english: 'Welcome', swedish: 'Välkommen' },
      { english: 'Happy birthday', swedish: 'Grattis på födelsedagen' },
      { english: 'Merry Christmas', swedish: 'God jul' },
      { english: 'Happy New Year', swedish: 'Gott nytt år' },
      { english: 'Congratulations', swedish: 'Grattis' },
      { english: 'Good luck', swedish: 'Lycka till' },
      { english: 'Safe journey', swedish: 'Säker resa' },
    ],
  },
  {
    name: 'Directions',
    words: [
      { english: 'Where is the restroom?', swedish: 'Var är toaletten?' },
      { english: 'How do I get to the train station?', swedish: 'Hur kommer jag till tågstationen?' },
      { english: 'Is it far from here?', swedish: 'Är det långt härifrån?' },
      { english: 'I need a taxi', swedish: 'Jag behöver en taxi' },
      { english: 'Where is the nearest bus stop?', swedish: 'Var är närmaste busshållplats?' },
      { english: 'How much is a ticket?', swedish: 'Hur mycket kostar en biljett?' },
      { english: 'Can you help me?', swedish: 'Kan du hjälpa mig?' },
      { english: 'I am lost', swedish: 'Jag är vilse' },
      { english: 'Left', swedish: 'Vänster' },
      { english: 'Right', swedish: 'Höger' },
      { english: 'Straight ahead', swedish: 'Rakt fram' },
      { english: 'Near', swedish: 'Nära' },
      { english: 'Far', swedish: 'Långt bort' },
      { english: 'What time does the bus leave?', swedish: 'När går bussen?' },
      { english: 'Which platform?', swedish: 'Vilken perrong?' },
      { english: 'Turn left at the corner', swedish: 'Sväng vänster vid hörnet' },
      { english: 'Turn right at the traffic light', swedish: 'Sväng höger vid trafikljuset' },
      { english: 'Go straight for two blocks', swedish: 'Gå rakt fram i två kvarter' },
      { english: 'It’s on the left side', swedish: 'Det ligger på vänster sida' },
      { english: 'It’s on the right side', swedish: 'Det ligger på höger sida' },
      { english: 'Is there a map nearby?', swedish: 'Finns det en karta i närheten?' },
      { english: 'Can you show me on the map?', swedish: 'Kan du visa mig på kartan?' },
      { english: 'How long does it take to get there?', swedish: 'Hur lång tid tar det att komma dit?' },
      { english: 'I’d like to go to this address', swedish: 'Jag skulle vilja gå till den här adressen' },
      { english: 'Where can I find a bus?', swedish: 'Var kan jag hitta en buss?' },
      { english: 'Where is the nearest ATM?', swedish: 'Var är närmaste bankomat?' },
      { english: 'How far is the airport from here?', swedish: 'Hur långt är det till flygplatsen härifrån?' },
      { english: 'Are we close?', swedish: 'Är vi nära?' },
      { english: 'Is this the right way?', swedish: 'Är det här rätt väg?' },
    ],
  },
  {
    name: 'Shopping & Restaurants',
    words: [
      { english: 'How much does this cost?', swedish: 'Hur mycket kostar det här?' },
      { english: 'Can I pay with card?', swedish: 'Kan jag betala med kort?' },
      { english: 'Do you accept cash?', swedish: 'Tar ni kontanter?' },
      { english: 'Can I have the menu, please?', swedish: 'Kan jag få menyn, tack?' },
      { english: 'I would like to order...', swedish: 'Jag skulle vilja beställa...' },
      { english: 'The bill, please', swedish: 'Notan, tack' },
      { english: 'Do you have vegetarian food?', swedish: 'Har ni vegetarisk mat?' },
      { english: 'I am allergic to...', swedish: 'Jag är allergisk mot...' },
      { english: 'This is delicious!', swedish: 'Det här är utsökt!' },
      { english: 'A glass of water, please', swedish: 'Ett glas vatten, tack' },
      { english: 'Coffee, please', swedish: 'Kaffe, tack' },
      { english: 'I am just looking', swedish: 'Jag tittar bara' },
      { english: 'Can I try this on?', swedish: 'Kan jag prova den här?' },
      { english: 'What size is this?', swedish: 'Vilken storlek är det här?' },
      { english: 'Do you have this in another color?', swedish: 'Har ni den här i en annan färg?' },
      { english: 'I’d like a table for two', swedish: 'Jag skulle vilja ha ett bord för två' },
      { english: 'What are today’s specials?', swedish: 'Vad är dagens specialiteter?' },
      { english: 'Can you recommend something?', swedish: 'Kan du rekommendera något?' },
      { english: 'I would like this to go', swedish: 'Jag skulle vilja ha det här att ta med' },
      { english: 'Can I see the wine list?', swedish: 'Kan jag få se vinlistan?' },
      { english: 'Do you have any desserts?', swedish: 'Har ni några efterrätter?' },
      { english: 'I’ll have the same', swedish: 'Jag tar samma' },
      { english: 'I’d like to make a reservation', swedish: 'Jag skulle vilja göra en reservation' },
      { english: 'Is service included?', swedish: 'Ingår serviceavgift?' },
      { english: 'Can I have a takeout box?', swedish: 'Kan jag få en matlåda?' },
      { english: 'Where can I buy a souvenir?', swedish: 'Var kan jag köpa en souvenir?' },
      { english: 'Do you have any sales today?', swedish: 'Har ni några reor idag?' },
      { english: 'I’m looking for a gift', swedish: 'Jag letar efter en present' },
    ],
  },
  {
    name: 'Basic Phrases',
    words: [
      { english: 'I understand', swedish: 'Jag förstår' },
      { english: 'I don’t understand', swedish: 'Jag förstår inte' },
      { english: 'Could you repeat that?', swedish: 'Kan du upprepa det?' },
      { english: 'What does this mean?', swedish: 'Vad betyder det här?' },
      { english: 'I need help', swedish: 'Jag behöver hjälp' },
      { english: 'I like it', swedish: 'Jag gillar det' },
      { english: 'I don’t like it', swedish: 'Jag gillar det inte' },
      { english: 'I am learning Swedish', swedish: 'Jag lär mig svenska' },
      { english: 'Can you speak slowly?', swedish: 'Kan du prata långsamt?' },
      { english: 'Where are you from?', swedish: 'Var kommer du ifrån?' },
      { english: 'I am from...', swedish: 'Jag kommer från...' },
      { english: 'What do you do?', swedish: 'Vad gör du?' },
      { english: 'I work as...', swedish: 'Jag arbetar som...' },
      { english: 'How old are you?', swedish: 'Hur gammal är du?' },
      { english: 'I am ... years old', swedish: 'Jag är ... år gammal' },
      { english: 'Do you speak English?', swedish: 'Talar du engelska?' },
      { english: 'I’m just browsing', swedish: 'Jag tittar bara' },
      { english: 'I’ll take it', swedish: 'Jag tar den' },
      { english: 'That’s great!', swedish: 'Det är fantastiskt!' },
      { english: 'Sounds good', swedish: 'Det låter bra' },
      { english: 'Let’s go!', swedish: 'Låt oss gå!' },
      { english: 'I’m ready', swedish: 'Jag är redo' },
      { english: 'Let’s meet at...', swedish: 'Låt oss mötas vid...' },
      { english: 'I’m busy right now', swedish: 'Jag är upptagen just nu' },
      { english: 'Can I help you?', swedish: 'Kan jag hjälpa dig?' },
      { english: 'I need to go', swedish: 'Jag behöver gå' },
      { english: 'See you soon', swedish: 'Vi ses snart' },
    ],
  },
  {
    name: 'Daily Activities',
    words: [
      { english: 'I wake up at...', swedish: 'Jag vaknar klockan...' },
      { english: 'I go to work', swedish: 'Jag går till jobbet' },
      { english: 'I eat breakfast', swedish: 'Jag äter frukost' },
      { english: 'I take a shower', swedish: 'Jag tar en dusch' },
      { english: 'I go to bed', swedish: 'Jag går till sängs' },
      { english: 'I exercise', swedish: 'Jag tränar' },
      { english: 'I read a book', swedish: 'Jag läser en bok' },
      { english: 'I watch TV', swedish: 'Jag tittar på TV' },
      { english: 'I go shopping', swedish: 'Jag går och handlar' },
      { english: 'I cook dinner', swedish: 'Jag lagar middag' },
      { english: 'I clean the house', swedish: 'Jag städar huset' },
      { english: 'I do the laundry', swedish: 'Jag tvättar kläder' },
      { english: 'I listen to music', swedish: 'Jag lyssnar på musik' },
      { english: 'I spend time with family', swedish: 'Jag tillbringar tid med familjen' },
      { english: 'I play with my kids', swedish: 'Jag leker med mina barn' },
      { english: 'I take a walk', swedish: 'Jag tar en promenad' },
      { english: 'I relax at home', swedish: 'Jag kopplar av hemma' },
      { english: 'I write in my journal', swedish: 'Jag skriver i min dagbok' },
      { english: 'I visit friends', swedish: 'Jag besöker vänner' },
      { english: 'I go for a run', swedish: 'Jag går en löprunda' },
      { english: 'I do yoga', swedish: 'Jag gör yoga' },
      { english: 'I meditate', swedish: 'Jag mediterar' },
      { english: 'I plan my week', swedish: 'Jag planerar min vecka' },
      { english: 'I check my email', swedish: 'Jag kollar min e-post' },
      { english: 'I go to the gym', swedish: 'Jag går till gymmet' },
      { english: 'I take care of my pets', swedish: 'Jag tar hand om mina husdjur' },
    ],
  },
  {
    name: 'Feelings & Emotions',
    words: [
      { english: 'I feel happy', swedish: 'Jag känner mig glad' },
      { english: 'I feel sad', swedish: 'Jag känner mig ledsen' },
      { english: 'I feel angry', swedish: 'Jag känner mig arg' },
      { english: 'I feel scared', swedish: 'Jag känner mig rädd' },
      { english: 'I feel excited', swedish: 'Jag känner mig exalterad' },
      { english: 'I feel tired', swedish: 'Jag känner mig trött' },
      { english: 'I feel stressed', swedish: 'Jag känner mig stressad' },
      { english: 'I feel grateful', swedish: 'Jag känner mig tacksam' },
      { english: 'I feel lonely', swedish: 'Jag känner mig ensam' },
      { english: 'I feel confused', swedish: 'Jag känner mig förvirrad' },
      { english: 'I feel proud', swedish: 'Jag känner mig stolt' },
      { english: 'I feel relaxed', swedish: 'Jag känner mig avslappnad' },
      { english: 'I feel bored', swedish: 'Jag känner mig uttråkad' },
      { english: 'I feel inspired', swedish: 'Jag känner mig inspirerad' },
      { english: 'I feel hopeful', swedish: 'Jag känner mig hoppfull' },
      { english: 'I feel motivated', swedish: 'Jag känner mig motiverad' },
      { english: 'I feel loved', swedish: 'Jag känner mig älskad' },
      { english: 'I feel safe', swedish: 'Jag känner mig säker' },
      { english: 'I feel valued', swedish: 'Jag känner mig värderad' },
      { english: 'I feel accepted', swedish: 'Jag känner mig accepterad' },
      { english: 'I feel different', swedish: 'Jag känner mig annorlunda' },
      { english: 'I feel fulfilled', swedish: 'Jag känner mig tillfredsställd' },
      { english: 'I feel anxious', swedish: 'Jag känner mig orolig' },
      { english: 'I feel curious', swedish: 'Jag känner mig nyfiken' },
      { english: 'I feel like celebrating', swedish: 'Jag känner för att fira' },
    ],
  },
  {
    name: 'Travel & Culture',
    words: [
      { english: 'I love traveling', swedish: 'Jag älskar att resa' },
      { english: 'The food is amazing', swedish: 'Maten är fantastisk' },
      { english: 'The people are friendly', swedish: 'Folk är vänliga' },
      { english: 'I enjoy visiting museums', swedish: 'Jag gillar att besöka museer' },
      { english: 'The landscape is beautiful', swedish: 'Landskapet är vackert' },
      { english: 'The culture is rich and diverse', swedish: 'Kulturen är rik och mångsidig' },
      { english: 'Sweden is known for its innovation', swedish: 'Sverige är känt för sin innovation' },
      { english: 'The people value work-life balance', swedish: 'Folket värdesätter balans mellan arbete och liv' },
      { english: 'I appreciate Swedish design', swedish: 'Jag uppskattar svensk design' },
      { english: 'The Swedish language is beautiful', swedish: 'Svenska språket är vackert' },
      { english: 'Nature is an important part of Swedish life', swedish: 'Naturen är en viktig del av svenskt liv' },
      { english: 'Sweden has many historical sites', swedish: 'Sverige har många historiska platser' },
      { english: 'I love Swedish music', swedish: 'Jag älskar svensk musik' },
      { english: 'Sweden has a strong commitment to sustainability', swedish: 'Sverige har ett starkt engagemang för hållbarhet' },
      { english: 'Swedish festivals are lively and fun', swedish: 'Svenska festivaler är livliga och roliga' },
      { english: 'The right to roam (Allemansrätten) is unique', swedish: 'Allemansrätten är unik' },
      { english: 'Swedes enjoy outdoor activities', swedish: 'Svenskar gillar utomhusaktiviteter' },
      { english: 'The education system is well-regarded', swedish: 'Utbildningssystemet är välrenommerat' },
      { english: 'Sweden has a high standard of living', swedish: 'Sverige har en hög levnadsstandard' },
      { english: 'Swedes are known for their fika culture', swedish: 'Svenskar är kända för sin fikakultur' },
      { english: 'I’m interested in Swedish history', swedish: 'Jag är intresserad av svensk historia' },
      { english: 'Swedes celebrate Midsummer', swedish: 'Svenskar firar midsommar' },
      { english: 'Swedish winter sports are popular', swedish: 'Svenska vintersporter är populära' },
      { english: 'The archipelago is stunning', swedish: 'Skärgården är fantastisk' },
      { english: 'I enjoy learning about Swedish traditions', swedish: 'Jag gillar att lära mig om svenska traditioner' },
      { english: 'The Northern Lights are breathtaking', swedish: 'Norrskenet är häpnadsväckande' },
    ],
  },
  {
    name: 'Health & Well-being',
    words: [
      { english: 'I am feeling sick', swedish: 'Jag mår illa' },
      { english: 'I need to see a doctor', swedish: 'Jag behöver se en läkare' },
      { english: 'I have a headache', swedish: 'Jag har huvudvärk' },
      { english: 'I feel stressed', swedish: 'Jag känner mig stressad' },
      { english: 'I need some rest', swedish: 'Jag behöver vila' },
      { english: 'I exercise regularly', swedish: 'Jag tränar regelbundet' },
      { english: 'I eat healthy foods', swedish: 'Jag äter hälsosam mat' },
      { english: 'I drink enough water', swedish: 'Jag dricker tillräckligt med vatten' },
      { english: 'I sleep well', swedish: 'Jag sover bra' },
      { english: 'I practice mindfulness', swedish: 'Jag praktiserar mindfulness' },
      { english: 'I manage my stress', swedish: 'Jag hanterar min stress' },
      { english: 'I go for regular check-ups', swedish: 'Jag går på regelbundna kontroller' },
      { english: 'I take my medication', swedish: 'Jag tar min medicin' },
      { english: 'I am taking care of my mental health', swedish: 'Jag tar hand om min mentala hälsa' },
      { english: 'I visit the dentist regularly', swedish: 'Jag besöker tandläkaren regelbundet' },
      { english: 'I find time to relax', swedish: 'Jag hittar tid att koppla av' },
      { english: 'I try to get enough sleep', swedish: 'Jag försöker få tillräckligt med sömn' },
      { english: 'I feel energized', swedish: 'Jag känner mig energisk' },
      { english: 'I have a balanced diet', swedish: 'Jag har en balanserad kost' },
      { english: 'I practice yoga', swedish: 'Jag praktiserar yoga' },
      { english: 'I meditate daily', swedish: 'Jag mediterar dagligen' },
      { english: 'I avoid unhealthy habits', swedish: 'Jag undviker ohälsosamma vanor' },
      { english: 'I seek support when needed', swedish: 'Jag söker stöd när jag behöver' },
      { english: 'I engage in hobbies', swedish: 'Jag sysslar med hobbys' },
      { english: 'I enjoy nature walks', swedish: 'Jag njuter av naturpromenader' },
      { english: 'I am learning to manage my time better', swedish: 'Jag lär mig att hantera min tid bättre' },
    ],
  },
  {
    name: 'Education & Learning',
    words: [
      { english: 'I love learning new things', swedish: 'Jag älskar att lära mig nya saker' },
      { english: 'I attend classes', swedish: 'Jag går på lektioner' },
      { english: 'I study every day', swedish: 'Jag studerar varje dag' },
      { english: 'I read books', swedish: 'Jag läser böcker' },
      { english: 'I take notes', swedish: 'Jag tar anteckningar' },
      { english: 'I participate in discussions', swedish: 'Jag deltar i diskussioner' },
      { english: 'I do my homework', swedish: 'Jag gör mina läxor' },
      { english: 'I prepare for exams', swedish: 'Jag förbereder mig för prov' },
      { english: 'I work on group projects', swedish: 'Jag arbetar med grupprojekt' },
      { english: 'I use online resources', swedish: 'Jag använder online-resurser' },
      { english: 'I enjoy teaching others', swedish: 'Jag tycker om att lära ut till andra' },
      { english: 'I visit the library', swedish: 'Jag besöker biblioteket' },
      { english: 'I ask questions', swedish: 'Jag ställer frågor' },
      { english: 'I seek help when needed', swedish: 'Jag söker hjälp när jag behöver' },
      { english: 'I give presentations', swedish: 'Jag håller presentationer' },
      { english: 'I learn from my mistakes', swedish: 'Jag lär mig av mina misstag' },
      { english: 'I practice my skills', swedish: 'Jag övar mina färdigheter' },
      { english: 'I work with a mentor', swedish: 'Jag arbetar med en mentor' },
      { english: 'I engage in lifelong learning', swedish: 'Jag engagerar mig i livslångt lärande' },
      { english: 'I explore new subjects', swedish: 'Jag utforskar nya ämnen' },
      { english: 'I join study groups', swedish: 'Jag går med i studiegrupper' },
      { english: 'I set learning goals', swedish: 'Jag sätter inlärningsmål' },
      { english: 'I share knowledge with others', swedish: 'Jag delar kunskap med andra' },
      { english: 'I attend workshops', swedish: 'Jag går på workshops' },
      { english: 'I believe in lifelong education', swedish: 'Jag tror på livslång utbildning' },
    ],
  },
  {
    name: 'Nature & Environment',
    words: [
      { english: 'I love nature', swedish: 'Jag älskar naturen' },
      { english: 'The forest is beautiful', swedish: 'Skogen är vacker' },
      { english: 'I enjoy hiking', swedish: 'Jag gillar att vandra' },
      { english: 'I protect the environment', swedish: 'Jag skyddar miljön' },
      { english: 'I recycle regularly', swedish: 'Jag återvinner regelbundet' },
      { english: 'I plant trees', swedish: 'Jag planterar träd' },
      { english: 'I conserve water', swedish: 'Jag sparar vatten' },
      { english: 'I use public transport', swedish: 'Jag använder kollektivtrafik' },
      { english: 'I reduce plastic use', swedish: 'Jag minskar plastanvändningen' },
      { english: 'I participate in clean-up events', swedish: 'Jag deltar i städningsevent' },
      { english: 'I support wildlife conservation', swedish: 'Jag stödjer bevarande av vilda djur' },
      { english: 'I enjoy birdwatching', swedish: 'Jag tycker om fågelskådning' },
      { english: 'I like camping', swedish: 'Jag gillar att campa' },
      { english: 'I appreciate biodiversity', swedish: 'Jag uppskattar biologisk mångfald' },
      { english: 'I enjoy the beach', swedish: 'Jag njuter av stranden' },
      { english: 'I learn about ecosystems', swedish: 'Jag lär mig om ekosystem' },
      { english: 'I watch the sunset', swedish: 'Jag tittar på solnedgången' },
      { english: 'I support renewable energy', swedish: 'Jag stödjer förnybar energi' },
      { english: 'I visit national parks', swedish: 'Jag besöker nationalparker' },
      { english: 'I enjoy outdoor activities', swedish: 'Jag tycker om utomhusaktiviteter' },
      { english: 'I advocate for sustainability', swedish: 'Jag förespråkar hållbarhet' },
      { english: 'I explore nature trails', swedish: 'Jag utforskar naturstigar' },
      { english: 'I enjoy gardening', swedish: 'Jag tycker om att odla' },
      { english: 'I participate in nature workshops', swedish: 'Jag deltar i naturverkstäder' },
      { english: 'I love stargazing', swedish: 'Jag älskar att stjärnskåda' },
    ],
  },
  {
    name: 'Technology & Innovation',
    words: [
      { english: 'I love technology', swedish: 'Jag älskar teknologi' },
      { english: 'I use a smartphone', swedish: 'Jag använder en smartphone' },
      { english: 'I like to code', swedish: 'Jag gillar att koda' },
      { english: 'I enjoy using apps', swedish: 'Jag gillar att använda appar' },
      { english: 'I learn about new gadgets', swedish: 'Jag lär mig om nya prylar' },
      { english: 'I follow tech news', swedish: 'Jag följer tekniknyheter' },
      { english: 'I participate in online forums', swedish: 'Jag deltar i online-forum' },
      { english: 'I am interested in AI', swedish: 'Jag är intresserad av AI' },
      { english: 'I attend tech conferences', swedish: 'Jag går på teknik-konferenser' },
      { english: 'I build websites', swedish: 'Jag bygger webbplatser' },
      { english: 'I troubleshoot tech issues', swedish: 'Jag löser tekniska problem' },
      { english: 'I enjoy gaming', swedish: 'Jag gillar att spela spel' },
      { english: 'I use social media', swedish: 'Jag använder sociala medier' },
      { english: 'I keep my software updated', swedish: 'Jag håller min programvara uppdaterad' },
      { english: 'I explore virtual reality', swedish: 'Jag utforskar virtuell verklighet' },
      { english: 'I participate in hackathons', swedish: 'Jag deltar i hackathons' },
      { english: 'I enjoy digital art', swedish: 'Jag gillar digital konst' },
      { english: 'I study programming languages', swedish: 'Jag studerar programmeringsspråk' },
      { english: 'I use cloud storage', swedish: 'Jag använder molnlagring' },
      { english: 'I engage with tech communities', swedish: 'Jag deltar i teknikgemenskaper' },
      { english: 'I am learning about cybersecurity', swedish: 'Jag lär mig om cybersäkerhet' },
      { english: 'I advocate for digital literacy', swedish: 'Jag förespråkar digital kompetens' },
      { english: 'I enjoy online learning', swedish: 'Jag gillar att lära mig online' },
    ],
  },
  {
    name: 'Work & Career',
    words: [
      { english: 'I enjoy my job', swedish: 'Jag trivs på jobbet' },
      { english: 'I work full-time', swedish: 'Jag arbetar heltid' },
      { english: 'I am looking for a job', swedish: 'Jag söker jobb' },
      { english: 'I have an interview tomorrow', swedish: 'Jag har en intervju imorgon' },
      { english: 'I work in a team', swedish: 'Jag arbetar i ett team' },
      { english: 'I attend meetings', swedish: 'Jag går på möten' },
      { english: 'I set goals', swedish: 'Jag sätter mål' },
      { english: 'I manage my time well', swedish: 'Jag hanterar min tid bra' },
      { english: 'I communicate with colleagues', swedish: 'Jag kommunicerar med kollegor' },
      { english: 'I learn new skills', swedish: 'Jag lär mig nya färdigheter' },
      { english: 'I receive feedback', swedish: 'Jag får feedback' },
      { english: 'I work on projects', swedish: 'Jag arbetar med projekt' },
      { english: 'I celebrate achievements', swedish: 'Jag firar prestationer' },
      { english: 'I seek professional development', swedish: 'Jag söker professionell utveckling' },
      { english: 'I network with others', swedish: 'Jag nätverkar med andra' },
      { english: 'I balance work and life', swedish: 'Jag balanserar arbete och liv' },
      { english: 'I pursue my career goals', swedish: 'Jag strävar efter mina karriärmål' },
      { english: 'I take breaks', swedish: 'Jag tar pauser' },
      { english: 'I work remotely', swedish: 'Jag arbetar på distans' },
      { english: 'I value teamwork', swedish: 'Jag värderar teamwork' },
      { english: 'I adapt to change', swedish: 'Jag anpassar mig till förändringar' },
      { english: 'I focus on results', swedish: 'Jag fokuserar på resultat' },
      { english: 'I maintain a positive attitude', swedish: 'Jag upprätthåller en positiv attityd' },
      { english: 'I believe in work-life balance', swedish: 'Jag tror på balans mellan arbete och liv' },
      { english: 'I find meaning in my work', swedish: 'Jag hittar mening i mitt arbete' },
    ],
  },
];
